version: '3.8'

services:
  laravel.app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: monapp-laravel:prod
    restart: unless-stopped
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_HOST: mysql
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - mysql
    networks:
      - sail
    expose:
      - 9000

  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/var/www/html/public:ro
    depends_on:
      - laravel.app
    networks:
      - sail

volumes:
  sail-mysql:
    driver: local

networks:
  sail:
    driver: bridge
